enum chatActions {
  SET_CHAT_SUMMARY_LIST = 'SET_CHAT_SUMMARY_LIST',
  ADD_CHAT_SUMMARY = 'ADD_CHAT_SUMMARY',
  UPDATE_CHAT_SUMMARY = 'UPDATE_CHAT_SUMMARY',
  DELETE_CHAT_SUMMARY = 'DELETE_CHAT_SUMMARY',
  SET_MESSAGES = 'SET_MESSAGES',
  ADD_MESSAGE = 'ADD_MESSAGE',
  UPDATE_MESSAGE = 'UPDATE_MESSAGE',
  DELETE_MESSAGE = 'DELETE_MESSAGE',
}

export default chatActions;
